name: Build & Release APK

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd gestra
          flutter pub get

      - name: Flutter Doctor
        run: |
          flutter doctor -v

      -name: Install TFLite Native libs
        run: |
          cd gestra
          dart run tflite_flutter:install

      - name: Build APK
        run: |
          cd gestra
          flutter build apk --release

      - name: Create GitHub Release & Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: gestra/build/app/outputs/flutter-apk/app-release.apk
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}